version: 1.0.0.{build}
branches:
  only:
  - master

image: Visual Studio 2015

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

install: 
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t tools
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t platform-tools
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t build-tools-25.0.6
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t android-25
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t android-15

build_script:
- cmd: >-
    powershell .\bootstrapper.ps1 -Target package -Verbosity diagnostic

artifacts:
- path: ./output/*.nupkg
  name: NuGet    

deploy:
- provider: NuGet
  api_key:
    secure: vfqPJYqZeRWBxKkvKwFuoRrFpUGJVfTAmyzF/XQme/oQz0KcUlgF5a9gFEEomszg
  on:
    branch: master  