#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RendrKit.PromptSheet.Android.Resource", IsApplication=false)]

namespace RendrKit.PromptSheet.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public static int cardBackgroundColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public static int cardCornerRadius = 2130771973;
			
			// aapt resource value: 0x7f010006
			public static int cardElevation = 2130771974;
			
			// aapt resource value: 0x7f010007
			public static int cardMaxElevation = 2130771975;
			
			// aapt resource value: 0x7f010009
			public static int cardPreventCornerOverlap = 2130771977;
			
			// aapt resource value: 0x7f010008
			public static int cardUseCompatPadding = 2130771976;
			
			// aapt resource value: 0x7f01000a
			public static int contentPadding = 2130771978;
			
			// aapt resource value: 0x7f01000e
			public static int contentPaddingBottom = 2130771982;
			
			// aapt resource value: 0x7f01000b
			public static int contentPaddingLeft = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public static int contentPaddingRight = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public static int contentPaddingTop = 2130771981;
			
			// aapt resource value: 0x7f010000
			public static int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public static int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public static int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public static int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public static int cardview_dark_background = 2131034112;
			
			// aapt resource value: 0x7f050001
			public static int cardview_light_background = 2131034113;
			
			// aapt resource value: 0x7f050002
			public static int cardview_shadow_end_color = 2131034114;
			
			// aapt resource value: 0x7f050003
			public static int cardview_shadow_start_color = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f020003
			public static int cardview_compat_inset_shadow = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int cardview_default_elevation = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int cardview_default_radius = 2130837509;
			
			// aapt resource value: 0x7f020000
			public static int item_touch_helper_max_drag_scroll_per_frame = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int item_touch_helper_swipe_escape_max_velocity = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int item_touch_helper_swipe_escape_velocity = 2130837506;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f030000
			public static int item_touch_helper_previous_elevation = 2130903040;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public static int library_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040001
			public static int Base_CardView = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int CardView = 2130968576;
			
			// aapt resource value: 0x7f040002
			public static int CardView_Dark = 2130968578;
			
			// aapt resource value: 0x7f040003
			public static int CardView_Light = 2130968579;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 1
			public static int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public static int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public static int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public static int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public static int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public static int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public static int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public static int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public static int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public static int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public static int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public static int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public static int CardView_contentPaddingTop = 11;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public static int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public static int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public static int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public static int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public static int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
